name: Build and Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  make_pdf:
    runs-on: ubuntu-18.04
    steps:
      - name: create file list
        id: files_list
        run: |
          shopt -s extglob
          cd $GITHUB_WORKSPACE
          mkdir output  # create output dir
          echo "files=$(printf '"%s" ' !(README).md)" >> $GITHUB_OUTPUT
          shopt -u extglob
      - uses: docker://pandoc/latex:2.9
        with:
          args: "-V fontfamily:ClearSans -V fontfamilyoptions:sfdefault --toc -o 'output/fim-queueing-docs.pdf' ${{ steps.files_list.outputs.files }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "FIM Queueing Documentation Release ${{ env.GITHUB_RUN_NUMBER }}"
          files: |
            output/fim-queueing-docs.pdf
    
