name: Build and Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  make_pdf:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: create file list
        id: files_list
        run: |
          shopt -s extglob
          cd $GITHUB_WORKSPACE
          mkdir output  # create output dir
          echo "files=$(printf '"%s" ' !(README).md)" >> $GITHUB_OUTPUT
          shopt -u extglob
      - uses: docker://pandoc/latex:2.9
        with:
          args: "--toc -o output/fim-queueing-docs.pdf ${{ steps.files_list.outputs.files }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "FIM Queueing Documentation Release ${{ github.run_number }}"
          files: |
            output/fim-queueing-docs.pdf
  deploy:
    needs: make_pdf
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Copy index
        run: |
          cp index.html output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: './output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1







